os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get upgrade
  - make install_deps
  - source setup.bash
script:
  - make && make test
