os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
install:
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  # See http://stackoverflow.com/questions/33196136/travis-ci-update-cmake-using-the-packages-cache
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
  - make install_deps
  - source setup.bash
script:
  - make && make test
